[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
log = "0.4"
simple_logger = "1.13"
redis = "0.21"
kafka = "0.13"
tch = "0.4"
hyper = "0.14"
tokio = { version = "1", features = ["full"] }
